/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // SunFoods Organic Brand Colors
        'sunrise-leaf': {
          DEFAULT: '#1F7A4D',
          50: '#E8F5EE',
          100: '#D1EBE0',
          200: '#A3D7C1',
          300: '#75C3A2',
          400: '#47AF83',
          500: '#1F7A4D',
          600: '#19623E',
          700: '#134A2E',
          800: '#0D311F',
          900: '#06190F',
        },
        'warm-sun': {
          DEFAULT: '#FFC145',
          50: '#FFF9EB',
          100: '#FFF3D6',
          200: '#FFE7AD',
          300: '#FFDB84',
          400: '#FFCF5B',
          500: '#FFC145',
          600: '#F5A200',
          700: '#BD7D00',
          800: '#855800',
          900: '#4D3300',
        },
        'fresh-soil': {
          DEFAULT: '#6B4F1D',
          50: '#F5F0E8',
          100: '#EBE1D1',
          200: '#D7C3A3',
          300: '#C3A575',
          400: '#AF8747',
          500: '#6B4F1D',
          600: '#563F17',
          700: '#402F11',
          800: '#2B200B',
          900: '#161005',
        },
        'neutral-mist': {
          DEFAULT: '#F5F7F4',
          50: '#FFFFFF',
          100: '#FCFDFB',
          200: '#F5F7F4',
          300: '#E8ECE5',
          400: '#DBE1D6',
          500: '#CED6C7',
          600: '#B0BCA5',
          700: '#8D9D7C',
          800: '#6A7E53',
          900: '#47602A',
        },
        // Category Colors
        'category-vegetables': '#6CC24A',
        'category-fruits': '#FF7043',
        'category-pantry': '#F2C94C',
        'category-wellness': '#7F8C8D',
        // Trầm Hương Luxury Theme - Bronze & Brown
        'luxury-bronze': {
          DEFAULT: '#C1A875',
          50: '#FAF8F3',
          100: '#F0EBE0',
          200: '#E5DDCA',
          300: '#D9CEB4',
          400: '#CDB89E',
          500: '#C1A875',
          600: '#B39555',
          700: '#8F7745',
          800: '#6B5935',
          900: '#473C24',
        },
        'luxury-brown': {
          DEFAULT: '#3D2B1F',
          50: '#F5F1EE',
          100: '#E8E0D9',
          200: '#D1C1B3',
          300: '#B9A28D',
          400: '#A28367',
          500: '#6B543F',
          600: '#3D2B1F',
          700: '#2E2017',
          800: '#1F1610',
          900: '#100B08',
        },
      },
      fontFamily: {
        // Heading font - Friendly and rounded for organic feel
        display: ['var(--font-display)', 'system-ui', '-apple-system', 'sans-serif'],
        // Body font - Highly legible for Vietnamese content
        sans: ['var(--font-sans)', 'Inter', 'system-ui', '-apple-system', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['3.5rem', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg': ['3rem', { lineHeight: '1.15', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-md': ['2.25rem', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-sm': ['1.875rem', { lineHeight: '1.25', letterSpacing: '-0.01em', fontWeight: '600' }],
        'heading-lg': ['1.5rem', { lineHeight: '1.3', fontWeight: '600' }],
        'heading-md': ['1.25rem', { lineHeight: '1.35', fontWeight: '600' }],
        'heading-sm': ['1.125rem', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['1.125rem', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['1rem', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['0.875rem', { lineHeight: '1.5', fontWeight: '400' }],
        'caption': ['0.75rem', { lineHeight: '1.4', fontWeight: '400' }],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}